# This is a basic workflow to help you get started with Actions

name: Create release

# Controls when the workflow will run
on:
  pull_request_target:
    branches: 
      - 'main'
    types:
      - closed
permissions: write-all
env:
  GH_TOKEN: ${{ github.token }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Pods cache
        id: cache-pods
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - if: steps.cache-pods.outputs.cache-hit != 'true'
        name: Pod install
        run: pod install --repo-update
      - name: Print pods
        run: |
          ls
          ls Pods
      - name: Save version number
        run: |
          echo "VERSION=1.1.0" >> $GITHUB_ENV
      - name: Create release
        run: gh release create "$VERSION" --generate-notes
